name: Notebook to Blog Post
on: 'push'
#   push:
#     branches:
#       - master
#     paths:
#       - '_notebooks/*.ipynb'

jobs:
  convert-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master

    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    
    - name: Run notebook converter
      run: |
        chmod -R 777 _posts/
        pip install --upgrade pip
        pip install git+https://github.com/fastai/nbdev.git
        nbdev_install_git_hooks
        python _action_files/nb2post.py
    
    - name: Look at files
      run: |
        ls _posts/
      
    - name: commit & push files
      run: |
        git config --global user.name $GITHUB_ACTOR
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        git add _posts
        git commit -m "Update Jupyter Blog Posts" --allow-empty
        git push github HEAD:${GITHUB_REF}